feniks/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
import oembed
oembed.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'feniks.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('pages.urls')),
    url(r'^about/', include('pages.urls')),
    url(r'^documents/', include('documents.urls')),
    url(r'^gallery/', include('photos.urls')),
    url(r'^contacts/', include('feedback_app.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += patterns('',
       url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
           {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )


urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),
)

pages/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'feniks.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'pages.views.home', name='home'),
    url(r'^history_page/', 'pages.views.history', name='history'),

]

from django.conf.urls import patterns, url
import oembed


urlpatterns = patterns('pages.views',
    # indexes
    url(r'^$', 'index', name='news_index'),
    # url(r'^category/(?P<id>\d+)-(?P<slug>[-\w]+)/$', 'category', name='blog_category'),

    # archives
    url(r'^archive/(?P<year>\d{4})/$', 'archive_year', name='news_archive_year'),
    url(r'^archive/(?P<year>\d{4})/(?P<month>\d{2})/$', 'archive_month', name='news_archive_month'),
    url(r'^archive/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', 'archive_day', name='news_archive_day'),

    # details
    url(r'^details/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', 'details', name='news_details'),
)

photos/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView
from photos.models import Album, Photo
#
urlpatterns = patterns('',
          url(r'^$', ListView.as_view(
            model=Album,
            context_object_name='my_album',
            template_name='photos/album.html'),
            name='gallery'
            ),
          url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(
            model=Album,
            context_object_name='photos',
            template_name='photos/photo.html'),
            name='photos'
            ),
)

photos/models.py
#! coding: utf-8
from django.db import models
#Альбом с фотографиями
class Album(models.Model):
    title = models.CharField("Название альбома", max_length=100)
    slug = models.SlugField("Ссылка для альбома", max_length=100, unique=True)
    img = models.ImageField("Изображение альбома", upload_to='images',
    help_text='Размер изображения 200px на 200px')

    class Meta:
        ordering = ['title']
        verbose_name = 'Альбом'
        verbose_name_plural = 'Альбомы'

    def __unicode__(self):
        return self.title
#Фотографии в альбоме
class Photo(models.Model):
    title = models.CharField("Название фотографии", max_length=100)
    album = models.ForeignKey(Album, verbose_name='Альбом')
    img = models.ImageField("Фото", upload_to='images',
	help_text='Желательно, чтоб фото было не большого размера')

    class Meta:
        ordering = ['title']
        verbose_name = 'Фото'
        verbose_name_plural = "Фотографии"
        
    def __unicode__(self):
        return self.title

photos/views.py
from django.shortcuts import render

# Create your views here.

photos/templates/photos/album.html
{% extends 'pages/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}Фото{% endblock %}


{% block content %}
<article class="gallery">
  <div id="content_box-photos">

    <ul class="photos-1">
        <h3>Фотогалерея</h3>
						<li class="widget widget-sidebar">
              <div class="ad-125-photos">
                <ul>
                  {% for album in my_album %}
                  <li class="oddad"><a href="{{ album.slug }}">
                    {% thumbnail album.img "200x200" crop='center' as im %}
                    <img src="{{ im.url }}" alt="{{ im.title }}" width="{{ im.width }}" height="{{ im.height }}">
                      {% endthumbnail %}
                  </a>
                  <p>{{ album.title }}</p>
                </li>
                  {% endfor %}
                </ul>
              </div>
            </li>
					</ul>
  </div>
</article>
{% endblock %}


{% block script %}
    <script type="text/javascript">
    $(document).ready(function(){
        var photo_title = $("div.album p");
        var album = $("div.album");
        photo_title.hide();
        album.hover(
                function(){
                    $(this).css({"backgroundColor":"#fff"});
                    photo_title.show();
                },
                function(){
                    photo_title.hide();
                    $(this).css({"backgroundColor": ""});
                }
        );
    });
    </script>
{% endblock %}

photos/templates/photos/photo.html
{% extends 'pages/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}Фото{% endblock %}

{% block content %}
<article class="gallery">
  <div id="content_box-photos">

    <ul class="photos-1">
        <h3>Фотогалерея</h3>

						<li class="widget widget-sidebar">
              <div class="ad-125-photos">
                <ul>
                  {% for photo in photos.photo_set.all %}
                  <li class="oddad">
                    <a href="/media/{{ photo.img }}" rel="prettyPhoto[pp_gal]">
                    {% thumbnail photo.img "150x150" crop='center' as im %}
                    <img src="{{ im.url }}" alt="{{ photo.title }}" width="{{ im.width }}" height="{{ im.height }}">
                    {% endthumbnail %}
                  </a>
                  <p>{{ photo.title }}</p>
                </li>
                  {% endfor %}
                </ul>
              </div>
            </li>


					</ul>
  </div>
</article>
{% endblock %}